services:
  - type: web
    name: shopping-app
    env: docker
    plan: free
    buildCommand: docker build -t shopping-app .
    startCommand: php artisan octane:start --server=swoole --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stderr
      - key: OCTANE_SERVER
        value: swoole
      - key: REDIS_HOST
        fromService:
          type: redis
          name: shopping-cache
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: shopping-cache
          property: port

  - type: redis
    name: shopping-cache
    plan: free
    ipAllowList: [] # Access only from within Render
